# Generated by Django 5.1 on 2026-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='categoria',
            field=models.CharField(choices=[('Bolos', 'Bolos'), ('Cupcakes', 'Cupcakes'), ('Doces', 'Doces'), ('Bolos no Pote', 'Bolos no Pote'), ('Outros', 'Outros')], default='Bolos', max_length=32),
        ),
    ]
