# Generated by Django 5.1 on 2026-05-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_bolo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='tamanho_padrao',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='categoria',
            field=models.CharField(choices=[('Bolos', 'Bolos'), ('Cupcakes', 'Cupcakes'), ('Doces', 'Doces'), ('Bolos no Pote', 'Bolos no Pote'), ('Outros', 'Outros')], default='Doces', max_length=32),
        ),
    ]
