# Generated by assistant to add avaliacao field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_bolo_tamanho_padrao_alter_bolo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='avaliacao',
            field=models.IntegerField(default=5),
        ),
    ]
